version: '3.7'
services:
  composer:
    container_name: rna_as_api_composer
    image: composer:1.9
    working_dir: /application
    volumes:
      - ./:/application
  php:
    container_name: rna_as_api_php
    image: php:7.2
    working_dir: /application
    volumes:
      - ./:/application
